texts_dir: "/app/TG/Data/Textgroup"
language: ru

proxy:
  type: none

groups:
  uslugi_irkutsk:
    time: 1.1
    language: ru
  Freelancechat2:
    time: 1.2
    language: ru
  dubay_chat:
    time: 2
    language: ru
  jess_chat:
    time: 1.3
    language: ru
  freelance_chatik0:
    time: 2
    language: ru
